<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenTK.Windowing.Desktop" Version="5.0.0-pre.16"/>
        <PackageReference Include="TorchSharp" Version="0.107.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiSAM.Core\LiSAM.Core.csproj"/>
        <ProjectReference Include="..\LiSAM.Visualization\LiSAM.Visualization.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\dataset\**" CopyToOutputDirectory="PreserveNewest" LinkBase="dataset\"/>
    </ItemGroup>
</Project>
